In [4]:
# 필요패키지 import
import time
import json
import urllib
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup

In [6]:
#데이터 담는 곳
desc_list = []

for num in range(21,25):
#딜레이    
    seed = np.random.randint(100)
    np.random.seed(seed)
    a = np.random.randint(1) + round(np.random.random(),2)
    time.sleep(a)

#욕설신고 게시판 제목 크롤링
    url = f'https://www.inven.co.kr/board/lol/2771?category=%EC%9A%95%EC%84%A4&p={num}'
    resp = requests.get(url)
    html = BeautifulSoup(resp.text, 'html.parser')
    for news in html.select('td.tit'):
        desc_list.append(news.text.strip().replace('\t','').replace('\n',''))

In [7]:
len(desc_list)

240

In [11]:
nick_list = []
for i in range(0,240):
    nick_list.append(desc_list[i].split())

In [5]:
nick_df = pd.DataFrame(nick_list)

NameError: name 'nick_list' is not defined

In [15]:
nick_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,[욕설],[박제]Jea,Hyeon00,위안부드립침,전번깜,01085571284,None,None,None,None,None,None,None,None
1,[욕설],트롤러와,패드립퍼듀오,박제,시킵니다,None,None,None,None,None,None,None,None,None
2,[욕설],WYBH,GIRIBOYZ,<<--트롤,욕설,박제요,사진,None,None,None,None,None,None,None
3,[욕설],shotgun25,갑자기,욕,박음,None,None,None,None,None,None,None,None,None
4,[욕설],Anyvitaus,패드립,박제,사진,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,[욕설],play,yasuo,best,패드립,[3],None,None,None,None,None,None,None,None
236,[욕설],김혜진,내노예,<<패작러,제보,사진,None,None,None,None,None,None,None,None
237,[욕설],96윤동현,이거부캐임트롤함,패드립,[2],None,None,None,None,None,None,None,None,None
238,[욕설],롤겜하다가,None,None,None,None,None,None,None,None,None,None,None,None
239,[욕설],포항,이즈리얼,<-,미드,룰루,하고,랭에서,트롤하는,트롤러,None,None,None,None

In [16]:
nick_df.to_csv('./nick_df1.csv', index=False)

In [6]:
#전처리 데이터 불러오기
df = pd.read_csv('./raw220628.csv',
                 encoding='utf-8')

In [7]:
df

            Column2
0               턱돼지
1          핑찍으면우물잠수
2     Visual Jockey
3               이원일
4              mvp맨
...             ...
1108        관악산오리백숙
1109           T1테뒤
1110         문란한사생활
1111          카와이민성
1112          콜라마신다

[1113 rows x 1 columns]

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1113 entries, 0 to 1112
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column2  1113 non-null   object
dtypes: object(1)
memory usage: 8.8+ KB

In [32]:
df.value_counts()

Column2
0티어나르      1
양파맛우유      1
어린왕자지완     1
어른아이님      1
어떻게성이류야    1
          ..
내고추한라산     1
내꿈은뜨뜨뜨뜨    1
내루트따라줘     1
내마눌김새론     1
힐주랑        1
Length: 1113, dtype: int64

In [106]:
KDA = html.select('span.sc-1p49g2y-1')[3].text[:-7]
kill = KDA.split('/')[0]
death =  KDA.split('/')[1]
assist = KDA.split('/')[2]
[KDA, kill, death, assist]

['11 / 2 / 7', '11 ', ' 2 ', ' 7']

In [139]:
kill_pati = html.select('span.sc-1p49g2y-1')[3].text[-5:-1]
kill_pati

'9.00'

In [38]:
df

            Column2
0               턱돼지
1          핑찍으면우물잠수
2     Visual Jockey
3               이원일
4              mvp맨
...             ...
1108        관악산오리백숙
1109           T1테뒤
1110         문란한사생활
1111          카와이민성
1112          콜라마신다

[1113 rows x 1 columns]

In [44]:
def data_crawling(user_name):
#DB 유저 불러오기
    url = f'https://your.gg/kr/profile/{user_name}'
    resp = requests.get(url)
    html = BeautifulSoup(resp.text, 'html.parser')
#승패 크롤링
    for i in range(0,9):
        # 티어 크롤링
        # buiiz7-0 sc-1p3os9u-3 hCTbNr zMKXD
        tier = html.select('div span.sc-1p3os9u-3')[0].text.strip()
        # 승, 패 크롤링
        # buiiz7-0 d490eh-4 hCTbML dSQenp
        Win_lose = html.select('span.d490eh-4')[:10][i].text
        # KDA 크롤링
        # buiiz7-0 sc-1p49g2y-1 hNEJCS gLFnks
        KDA = html.select('span.sc-1p49g2y-1')[i*3].text[:-7]
        kill = KDA.split('/')[0]
        death =  KDA.split('/')[1]
        assist = KDA.split('/')[2]
        # 게임 시간 크롤링
        # buiiz7-0 d490eh-5 hNEJEN
        game_time = html.select('span.d490eh-5')[i].text
        # 챔피언 크롤링
        # sc-1xwhuw1-0 afFmu sc-1hmh1k6-4 dIKnaT
        champion =html.select('div.sc-1xwhuw1-0 img')[i*10]['alt']
        # 킬 관여율 크롤링
        kill_pati = html.select('span.sc-1p49g2y-1')[i*3].text[-5:-1]
        # 두번째 방법
        # your.gg의 게임 결과의 우측에 닉네임이 존재하는 순서를 통해 포지션 크롤링 하기
        # d490eh-10 dkiApC
        position = html.select('ul.d490eh-10 a')[4].text
        # 0~1 top
        # 2~3 jungle
        # 4~5 mid
        # 6~7 adc
        # 8~9 support
        data.append([ user_name, tier, Win_lose, champion, position, kill, death, assist, kill_pati ])

In [45]:
data_crawling('왼손페이커')

In [34]:
data = []

In [46]:
col_nm = ['유저명', '티어', '승패', '챔피언', '포지션', 'Kill', 'Death', 'Assist', '킬관여율']
pd.DataFrame(data,columns=col_nm)

         유저명          티어    승패       챔피언     포지션 Kill Death Assist  킬관여율
0   T1_faker  Challenger   WIN      Ahri  노는소년카티   2     4      16  4.50
1   T1_faker  Challenger  LOSS     Rakan  노는소년카티   4     7       4  1.14
2   T1_faker  Challenger  LOSS    Renata  노는소년카티   2     5      11  2.60
3   T1_faker  Challenger  LOSS    Ezreal  노는소년카티   1     7       9  1.43
4   T1_faker  Challenger   WIN    Ezreal  노는소년카티   6     4       1  1.75
5   T1_faker  Challenger   WIN    Akshan  노는소년카티  11     2       7  9.00
6   T1_faker  Challenger  LOSS     Akali  노는소년카티  10     5       4  2.80
7   T1_faker  Challenger  LOSS      Kayn  노는소년카티   6     4       6  3.00
8   T1_faker  Challenger   WIN     Diana  노는소년카티   7     5       4  2.20
9      왼손페이커      Gold 4  LOSS  MasterYi   나나킹받네   8    10      17  2.50
10     왼손페이커      Gold 4  LOSS    Anivia   나나킹받네   1     8       6  0.88
11     왼손페이커      Gold 4  LOSS  Nautilus   나나킹받네   4     6       5  1.50
12     왼손페이커      Gold 4   WIN      Jinx   나나킹받네   9     3       8  5.67
13     왼손페이커      Gold 4  LOSS   Caitlyn   나나킹받네   0     6       1  0.17
14     왼손페이커      Gold 4  LOSS     Yasuo   나나킹받네   1     8       2  0.38
15     왼손페이커      Gold 4  LOSS     Galio   나나킹받네   1    11       1  0.18
16     왼손페이커      Gold 4  LOSS  Volibear   나나킹받네   3     8       0  0.38
17     왼손페이커      Gold 4   WIN     Diana   나나킹받네   1     3       0  0.33

In [39]:
data = []
#DB 유저 불러오기
for i in range(0,2):
    user_name = (df['Column2'][i])
    url = f'https://your.gg/kr/profile/{user_name}'
    resp = requests.get(url)
    html = BeautifulSoup(resp.text, 'html.parser')

def data_crawling(user_name):
#승패 크롤링
    for i in range(0,9):
        # 티어 크롤링
        # buiiz7-0 sc-1p3os9u-3 hCTbNr zMKXD
        tier = html.select('div span.sc-1p3os9u-3')[0].text.strip()
        # 승, 패 크롤링
        # buiiz7-0 d490eh-4 hCTbML dSQenp
        Win_lose = html.select('span.d490eh-4')[:10][i].text
        # KDA 크롤링
        # buiiz7-0 sc-1p49g2y-1 hNEJCS gLFnks
        KDA = html.select('span.sc-1p49g2y-1')[i*3].text[:-7]
        kill = KDA.split('/')[0]
        death =  KDA.split('/')[1]
        assist = KDA.split('/')[2]
        # 게임 시간 크롤링
        # buiiz7-0 d490eh-5 hNEJEN
        game_time = html.select('span.d490eh-5')[i].text
        # 챔피언 크롤링
        # sc-1xwhuw1-0 afFmu sc-1hmh1k6-4 dIKnaT
        champion =html.select('div.sc-1xwhuw1-0 img')[i*10]['alt']
        # 킬 관여율 크롤링
        kill_pati = html.select('span.sc-1p49g2y-1')[i*3].text[-5:-1]
        # 두번째 방법
        # your.gg의 게임 결과의 우측에 닉네임이 존재하는 순서를 통해 포지션 크롤링 하기
        # d490eh-10 dkiApC
        position = html.select('ul.d490eh-10 a')[4].text
        # 0~1 top
        # 2~3 jungle
        # 4~5 mid
        # 6~7 adc
        # 8~9 support
        data.append([ user_name, tier, Win_lose, champion, position, kill, death, assist, kill_pati ])

In [40]:
col_nm = ['유저명', '티어', '승패', '챔피언', '포지션', 'Kill', 'Death', 'Assist', '킬관여율']
pd.DataFrame(data,columns=col_nm)

Empty DataFrame
Columns: [유저명, 티어, 승패, 챔피언, 포지션, Kill, Death, Assist, 킬관여율]
Index: []

In [49]:
url = 'https://your.gg/kr/profile/왼손페이커'
resp = requests.get(url)
html = BeautifulSoup(resp.text, 'html.parser')
champion =html.select('div.sc-1xwhuw1-0 img')[22]
champion

In [65]:
for i in df['Column2'][0:2]:
    try :
        data_crawling(i)
    except:
        pass

0 jungle

C:\Users\Hote\AppData\Local\Temp\ipykernel_8148\672985313.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data.append([ ingame_id, tier, Win_lose, champion, position, kill, death, assist, kill_pati ])

1 jungle
2 jungle
3 jungle
4 jungle
5 jungle
6 adc
7 top
8 top
9 jungle
10 adc
11 top
12 mid
13 mid
14 support
15 jungle
16 support
17 mid
18 adc
19 support
20 mid
21 support
22 jungle
23 jungle
24 adc
25 top
26 jungle
27 top
28 top
29 adc
0 top
1 top
2 top
3 top
4 top
5 top
6 top
7 top
8 top
9 top
10 top
11 top
12 top
13 support
14 top
15 top
16 support
17 mid
18 top
19 top
20 jungle
21 support
22 mid
23 top
24 top
25 top
26 top
27 top
28 top
29 top

In [59]:
data = []

def data_crawling(user_name):
#DB 유저 불러오기
    url = f'https://your.gg/kr/profile/{user_name}'
    resp = requests.get(url)
    html = BeautifulSoup(resp.text, 'html.parser')
#승패 크롤링
    for i in range(30):
        # 티어 크롤링
        # buiiz7-0 sc-1p3os9u-3 hCTbNr zMKXD
        ingame_id = html.select('div.sc-15xrq75-3 span')[0].text.strip()
        tier = html.select('div span.sc-1p3os9u-3')[0].text.strip()
        # 승, 패 크롤링
        # buiiz7-0 d490eh-4 hCTbML dSQenp
        Win_lose = html.select('span.d490eh-4')[i].text
        # KDA 크롤링
        # buiiz7-0 sc-1p49g2y-1 hNEJCS gLFnks
        KDA = html.select('span.sc-1p49g2y-1')[i*3].text[:-7]
        kill = KDA.split('/')[0]
        death =  KDA.split('/')[1]
        assist = KDA.split('/')[2]
        # 게임 시간 크롤링
        # buiiz7-0 d490eh-5 hNEJEN
        game_time = html.select('span.d490eh-5')[i].text
        # 챔피언 크롤링
        # sc-1xwhuw1-0 afFmu sc-1hmh1k6-4 dIKnaT
        champion =html.select('div.sc-1xwhuw1-0 img')[i*11]['alt']
        # 킬 관여율 크롤링
        kill_pati = html.select('span.sc-1p49g2y-1')[i*3].text[-5:-1]
        # 두번째 방법
        # your.gg의 게임 결과의 우측에 닉네임이 존재하는 순서를 통해 포지션 크롤링 하기
        # d490eh-10 dkiApC
        users = []
        for j in html.select('ul.d490eh-10 a'):
            users.append(j.text)
        if users[10*i:10*(i+1)].index(ingame_id) == 0 or users[10*i:10*(i+1)].index(ingame_id) == 1:
            position = 'top'
        elif users[10*i:10*(i+1)].index(ingame_id) == 2 or users[10*i:10*(i+1)].index(ingame_id) == 3:
            position = 'jungle'
        elif users[10*i:10*(i+1)].index(ingame_id) == 4 or users[10*i:10*(i+1)].index(ingame_id) == 5:
            position = 'mid'
        elif users[10*i:10*(i+1)].index(ingame_id) == 6 or users[10*i:10*(i+1)].index(ingame_id) == 7:
            position = 'adc'
        else:
            position = 'support'
        print(i, position)
        # 0~1 top
        # 2~3 jungle
        # 4~5 mid
        # 6~7 adc
        # 8~9 support
        data.append([ ingame_id, tier, Win_lose, champion, position, kill, death, assist, kill_pati ])

In [60]:
data_crawling('왼손페이커')

0 adc
1 support
2 top
3 top
4 adc
5 jungle
6 top
7 top
8 mid
9 top
10 support
11 support
12 support
13 support
14 adc
15 support
16 support
17 top
18 jungle
19 mid
20 support
21 jungle
22 adc
23 jungle
24 top

IndexError: list index out of range

In [63]:
col_nm = ['유저명', '티어', '승패', '챔피언', '포지션', 'Kill', 'Death', 'Assist', '킬관여율']
data = pd.DataFrame(data,columns=col_nm)
data

       유저명      티어    승패         챔피언      포지션 Kill Death Assist  킬관여율
0   왼손 페이커  Gold 4  LOSS    MasterYi      adc   8    10      17  2.50
1   왼손 페이커  Gold 4  LOSS  Blitzcrank  support   1     8       6  0.88
2   왼손 페이커  Gold 4  LOSS      Illaoi      top   4     6       5  1.50
3   왼손 페이커  Gold 4   WIN       Teemo      top   9     3       8  5.67
4   왼손 페이커  Gold 4  LOSS        Ashe      adc   0     6       1  0.17
5   왼손 페이커  Gold 4  LOSS       Ivern   jungle   1     8       2  0.38
6   왼손 페이커  Gold 4  LOSS    Volibear      top   1    11       1  0.18
7   왼손 페이커  Gold 4  LOSS       Teemo      top   3     8       0  0.38
8   왼손 페이커  Gold 4   WIN      Illaoi      mid   1     3       0  0.33
9   왼손 페이커  Gold 4  LOSS      Illaoi      top   0    16       3  0.19
10  왼손 페이커  Gold 4   WIN  Blitzcrank  support   3     3       7  3.33
11  왼손 페이커  Gold 4  LOSS      Maokai  support   0     9       5  0.56
12  왼손 페이커  Gold 4   WIN      Maokai  support   3     9      16  2.11
13  왼손 페이커  Gold 4  LOSS      Maokai  support   7     6      12  3.17
14  왼손 페이커  Gold 4  LOSS        Jinx      adc   2     6       6  1.33
15  왼손 페이커  Gold 4   WIN        Nami  support   0     4      13  3.25
16  왼손 페이커  Gold 4   WIN        Nami  support   3    10       9  1.20
17  왼손 페이커  Gold 4   WIN    Malphite      top   4     7      11  2.14
18  왼손 페이커  Gold 4  LOSS    Volibear   jungle   1     6       0  0.17
19  왼손 페이커  Gold 4   WIN        Ashe      mid   0     0       0  0.00
20  왼손 페이커  Gold 4  LOSS        Ashe  support   2     4       7  2.25
21  왼손 페이커  Gold 4  LOSS        Ahri   jungle   6     9      11  1.89
22  왼손 페이커  Gold 4  LOSS       Varus      adc   4     6       0  0.67
23  왼손 페이커  Gold 4  LOSS     Shyvana   jungle   6     8       7  1.63
24  왼손 페이커  Gold 4  LOSS      Illaoi      top   6     5       2  1.60